### ISSUE TITLE
Disable LS when on Kerbin, below a certain altitude

### ISSUE THREAD

**Issue by linuxgurugamer** [linuxgurugamer/IFI-Life-Support#4]

**Comment by swjr-swis** [comment]
Good idea, but if I may suggest something: allow for LS to still work when under water - subs or ocean bases should still require LS.

**Comment by linuxgurugamer** [comment]
It should already do that.  Have you tried it?

**Comment by linuxgurugamer** [comment]
The mod already dealt with LS, it isn't disabled, but need is greatly reduced.
