### ISSUE TITLE
toggler for hide slurry and sludge tanks

### ISSUE THREAD

**Issue by yalov** [linuxgurugamer/IFI-Life-Support#5]
"Show recyclers" toggle may be helpful for someone, but I was talking about a toggle for hide **just slurry and sludge tanks**. ("Show recyclers" toggle hides the tanks **and recycling parts**)  

The best place for toggler is difficulty settings, because is one-time-toggle at my game experience.

**Comment by linuxgurugamer** [comment]
It doesn't make sense to show the recycling parts without the tanks.
And, this is something that would need to be changed during a game, so it doesn't belong in the settings.

**Comment by yalov** [comment]
Why someone need slurry and sludge tanks for 100%-recycle ship and **simple** game experience?
It is LS tank + GreenHouse + MicroBiome. That is all.

**Comment by linuxgurugamer** [comment]
The parts don't have to be used. It's not many, and if someone is using the GreenHouse and MicroBiome, then there is a reason to have tanks for what they are processing, especially if you have higher usage than recycle capacity, otherwise excess just gets discarded

**Comment by yalov** [comment]
Hm... That's a thing. It is a lot of them. 20. Compare to 9 in USILS. 
If you always achieve higher recycle than usage then you always have slurry=0 sludge=0 and always 
 have no reason for these tanks.
 
Also,... is it possible to create combine tanks, what can contain LS, slurry, sludge, but limited by sum of them? Kerbals use LS, and then put slurry in the same tank (inside sealed little containers)

**Comment by linuxgurugamer** [comment]
I looked into combining, but had issues with IFS.

I'll think about it, but I don't think the mod should do it.  Maybe FilterExtensions or Janitor's Closet might be better.
